apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geo-app
  template:
    metadata:
      labels:
        app: geo-app
    spec:
      containers:
      - name: geo-app
        image: 536442977594.dkr.ecr.us-east-1.amazonaws.com/dev:latest

        ports:
        - containerPort: 80
